imports:
    - php

before_commands:
    - "composer install --dev --prefer-source --no-interaction"

filter:
    excluded_paths: [vendor/*, tests/*]

tools:
    php_code_coverage:
        test_command: ./vendor/bin/phpunit -c tests/
    php_code_sniffer:
        config:
            standard: PSR2
        filter:
            paths: [src/*, tests/*]
    php_sim: true
    php_cpd: false
    php_loc:
        enabled: true
        excluded_dirs: [tests, vendor]
    php_hhvm: true
    php_mess_detector:
        enabled: true
        filter:
            paths: [src/*]
    php_pdepend:
        enabled: true
        excluded_dirs: [tests, vendor]
    php_analyzer: true
    php_analyzer:
        filter:
            paths: [src/*, tests/*]
    sensiolabs_security_checker: true
    php_changetracking: true
