language: php

php:
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"
  - hhvm

install:
  - composer install --dev --no-interaction

script:
  - if [[ "$TRAVIS_PHP_VERSION" == "5.5" ]]; then ./vendor/bin/phpunit -c tests --coverage-clover=coverage.clover; fi
  - if [[ "$TRAVIS_PHP_VERSION" != "5.5" ]]; then ./vendor/bin/phpunit -c tests; fi

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" == "5.5" ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

